### ISSUE TITLE
Backport to Node.js v0.11.6?

### ISSUE THREAD

**Issue by mcandre** [ahmadnassri/echint#58]
When I try to run echint in older Node.js's, it mentions an error about a missing `assign` method.

Trace:

```
$ node_modules/.bin/echint lib/comments 

/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/echint/lib/index.js:34
  var opts = Object.assign({}, defaults);
                    ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at exports.default (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/echint/lib/index.js:34:21)
    at Object.<anonymous> (/Users/andrew/go/src/github.com/mcandre/comments/fish/node_modules/echint/lib/bin.js:34:16)
    at Module._compile (module.js:450:26)
    at Object.Module._extensions..js (module.js:468:10)
    at Module.load (module.js:350:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:491:10)
    at startup (node.js:119:16)
    at node.js:792:3

$ node_modules/.bin/echint --version
2.1.0

$ node --version
v0.11.6
```

**Comment by ahmadnassri** [comment]
since Node `v0.11.x` is no longer maintained, I'm not going to be adding any **official** support for any version less than `v4.x`.

this is already declared in the `package.json` as:

```json
"engines": {
  "node": ">=4"
}
```

I would recommend updating to Node `v4.x` if at all possible as the rest of the node community is already cutting support for their modules on anything lower.

understanding that sometimes that's not an option, you can always use [`babel`](https://github.com/babel/babel) to re-compile the `src` folder to a specific node version.
